# Generated by Django 5.0.1 on 2024-02-08 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='img_product',
            field=models.ImageField(blank=True, null=True, upload_to='product', verbose_name='Изображение'),
        ),
    ]
