# Generated by Django 5.0.1 on 2024-02-04 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authapp', '0001_initial'),
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_sum_order', models.DecimalField(decimal_places=2, max_digits=8)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('good_id', models.ManyToManyField(to='mainapp.goods')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapp.client')),
            ],
            options={
                'verbose_name': ' заказ',
                'verbose_name_plural': 'заказы',
            },
        ),
    ]
