# Generated by Django 5.0.1 on 2024-02-13 20:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authapp', '0001_initial'),
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_sum_order', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapp.client')),
            ],
            options={
                'verbose_name': ' заказ',
                'verbose_name_plural': 'заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_count', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('good_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.goods')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordersapp.order')),
            ],
            options={
                'verbose_name': 'ордер заказа',
                'verbose_name_plural': 'ордер заказов',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='good_id',
            field=models.ManyToManyField(through='ordersapp.OrderCard', to='mainapp.goods'),
        ),
    ]
