# Generated by Django 5.0.1 on 2024-02-13 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('email', models.EmailField(max_length=100, verbose_name='email')),
                ('phone_number', models.PositiveIntegerField(verbose_name='номер телефона')),
                ('address', models.TextField(verbose_name='адрес регистрации')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='дата регистрации')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
            },
        ),
    ]
